services:
  myDB:
    image: postgres
    container_name: nextjs-web
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fundacion_faca
    volumes:
      - ./postgres:/var/lib/postgresql/data