import { IUser } from "@/types/common";

export const users: IUser[] = [
    {
      nationalId: '1000000001',
      firstName: 'Lucía',
      lastName: 'Herrera',
      email: 'lucia.herrera@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000002',
      firstName: 'Carlos',
      lastName: 'Martínez',
      email: 'carlos.martinez@gmail.com',
      role: 'ADMIN',
      status: true,
    },
    {
      nationalId: '1000000003',
      firstName: 'María',
      lastName: 'López',
      email: 'maria.lopez@gmail.com',
      role: 'COORDINATOR',
      status: true,
    },
    {
      nationalId: '1000000004',
      firstName: 'Andrés',
      lastName: 'Vera',
      email: 'andres.vera@gmail.com',
      role: 'USER',
      status: false,
    },
    {
      nationalId: '1000000005',
      firstName: 'Valentina',
      lastName: 'Zamora',
      email: 'valentina.zamora@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000006',
      firstName: 'Mateo',
      lastName: 'Quintero',
      email: 'mateo.quintero@gmail.com',
      role: 'COORDINATOR',
      status: true,
    },
    {
      nationalId: '1000000007',
      firstName: 'Camila',
      lastName: 'Salazar',
      email: 'camila.salazar@gmail.com',
      role: 'ADMIN',
      status: false,
    },
    {
      nationalId: '1000000008',
      firstName: 'Juan',
      lastName: 'Moreno',
      email: 'juan.moreno@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000009',
      firstName: 'Sofía',
      lastName: 'Ortiz',
      email: 'sofia.ortiz@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000010',
      firstName: 'Diego',
      lastName: 'Navarro',
      email: 'diego.navarro@gmail.com',
      role: 'COORDINATOR',
      status: true,
    },
    {
      nationalId: '1000000011',
      firstName: 'Daniela',
      lastName: 'Ríos',
      email: 'daniela.rios@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000012',
      firstName: 'Sebastián',
      lastName: 'León',
      email: 'sebastian.leon@gmail.com',
      role: 'USER',
      status: false,
    },
    {
      nationalId: '1000000013',
      firstName: 'Ana',
      lastName: 'Gómez',
      email: 'ana.gomez@gmail.com',
      role: 'ADMIN',
      status: true,
    },
    {
      nationalId: '1000000014',
      firstName: 'Julián',
      lastName: 'Silva',
      email: 'julian.silva@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000015',
      firstName: 'Laura',
      lastName: 'Castillo',
      email: 'laura.castillo@gmail.com',
      role: 'COORDINATOR',
      status: true,
    },
    {
      nationalId: '1000000016',
      firstName: 'Tomás',
      lastName: 'Ibáñez',
      email: 'tomas.ibanez@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000017',
      firstName: 'Paula',
      lastName: 'Mendoza',
      email: 'paula.mendoza@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000018',
      firstName: 'Felipe',
      lastName: 'Rosales',
      email: 'felipe.rosales@gmail.com',
      role: 'ADMIN',
      status: true,
    },
    {
      nationalId: '1000000019',
      firstName: 'Isabella',
      lastName: 'Cárdenas',
      email: 'isabella.cardenas@gmail.com',
      role: 'USER',
      status: false,
    },
    {
      nationalId: '1000000020',
      firstName: 'Gabriel',
      lastName: 'Montoya',
      email: 'gabriel.montoya@gmail.com',
      role: 'COORDINATOR',
      status: true,
    },
    {
      nationalId: '1000000021',
      firstName: 'Nicole',
      lastName: 'Ramírez',
      email: 'nicole.ramirez@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000022',
      firstName: 'Santiago',
      lastName: 'Paredes',
      email: 'santiago.paredes@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000023',
      firstName: 'Renata',
      lastName: 'Cruz',
      email: 'renata.cruz@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000024',
      firstName: 'Emilio',
      lastName: 'Peña',
      email: 'emilio.pena@gmail.com',
      role: 'USER',
      status: false,
    },
    {
      nationalId: '1000000025',
      firstName: 'Mía',
      lastName: 'Pérez',
      email: 'mia.perez@gmail.com',
      role: 'ADMIN',
      status: true,
    },
    {
      nationalId: '1000000026',
      firstName: 'David',
      lastName: 'Torres',
      email: 'david.torres@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000027',
      firstName: 'Antonia',
      lastName: 'Ruiz',
      email: 'antonia.ruiz@gmail.com',
      role: 'COORDINATOR',
      status: true,
    },
    {
      nationalId: '1000000028',
      firstName: 'Maximiliano',
      lastName: 'Santos',
      email: 'max.santos@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000029',
      firstName: 'Emma',
      lastName: 'Valencia',
      email: 'emma.valencia@gmail.com',
      role: 'USER',
      status: true,
    },
    {
      nationalId: '1000000030',
      firstName: 'Bruno',
      lastName: 'Delgado',
      email: 'bruno.delgado@gmail.com',
      role: 'USER',
      status: true,
    },
  ];